version: '3'

services:
  test_db:
    image: postgres:12.2-alpine
    ports:
      - "42101:5432"
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: family_db
    logging:
      options:
        max-size: 500m
  db:
    image: postgres:12.2-alpine
    ports:
      - "42001:5432"
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: family_db
    logging:
      options:
        max-size: 500m
  migration:
    image: family_api
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd migrations; `PYTHONPATH=.. alembic upgrade head`'
    env_file:
      - .env
    environment:
      DATABASE_URI: "postgres://postgres:qwerty@db:5432/family_db"
    depends_on:
      - db
  web:
    image: family_api
    build: .
    command: gunicorn -b 0.0.0.0:5000 family_api.main:init_app --worker-class aiohttp.GunicornWebWorker
    env_file:
      - .env
    environment:
      DATABASE_URI: "postgres://postgres:qwerty@db:5432/family_db"
    volumes:
      - ./family_api:/code/family_api
      - ./migrations:/code/migrations
    ports:
      - "42002:5000"
    logging:
      options:
        max-size: 500m
    depends_on:
      - migration