# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  test_db:
    image: postgres:12.2-alpine
    ports:
      - "42101:5432"
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: family_db
    logging:
      options:
        max-size: 500m
  db:
    image: postgres:12.2-alpine
    ports:
      - "42001:5432"
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: family_db
    logging:
      options:
        max-size: 500m