"""add issued token table

Revision ID: ad8422e6f404
Revises: c7faac857973
Create Date: 2020-03-13 19:54:51.944345+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ad8422e6f404'
down_revision = 'c7faac857973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issued_token',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('token_type', sa.Enum('MEMBER_INVITATION', name='tokentype'), nullable=False),
                    sa.Column('token', sa.Text(), nullable=False),
                    sa.Column('expired_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issued_token')
    # ### end Alembic commands ###
