"""change uniquie constraint for family_member

Revision ID: c7faac857973
Revises: 5b53f508467b
Create Date: 2020-03-12 17:01:58.164368+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c7faac857973'
down_revision = '5b53f508467b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('family_member_family_id_user_uuid_uidx', 'family_member', ['family_id', 'user_uuid'])
    op.drop_index('ix_family_member_family_id', table_name='family_member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_family_member_family_id', 'family_member', ['family_id'], unique=False)
    op.drop_constraint('family_member_family_id_user_uuid_uidx', 'family_member', type_='unique')
    # ### end Alembic commands ###
