"""add issued token table related entity column

Revision ID: b5eb10ef4bc9
Revises: ad8422e6f404
Create Date: 2020-03-14 18:41:58.404647+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b5eb10ef4bc9'
down_revision = 'ad8422e6f404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issued_token', sa.Column('related_entity_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issued_token', 'related_entity_id')
    # ### end Alembic commands ###
