"""init base tables

Revision ID: 5b53f508467b
Revises: 
Create Date: 2020-03-08 17:56:50.975131+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b53f508467b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('baby',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('baby_uuid', postgresql.UUID(), nullable=False),
                    sa.Column('first_name', sa.Text(), nullable=False),
                    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
                    sa.Column('family_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(('family_id',), ['family.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('baby_uuid')
                    )
    op.create_index(op.f('ix_baby_family_id'), 'baby', ['family_id'], unique=False)
    op.create_table('family_member',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_uuid', postgresql.UUID(), nullable=False),
                    sa.Column('family_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(('family_id',), ['family.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_uuid')
                    )
    op.create_index(op.f('ix_family_member_family_id'), 'family_member', ['family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_member_family_id'), table_name='family_member')
    op.drop_table('family_member')
    op.drop_index(op.f('ix_baby_family_id'), table_name='baby')
    op.drop_table('baby')
    op.drop_table('family')
    # ### end Alembic commands ###
