version: '3'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: family_db
    logging:
      options:
        max-size: 500m
  lint:
    image: family_api
    build:
      context: ..
      dockerfile: ci/Dockerfile
    command: bash -c 'pylint family_api --rcfile=pylintrc 2>&1 | tee reports/pylint.txt'
    volumes:
      - ./reports:/code/reports
  migration:
    image: family_api
    build:
      context: ..
      dockerfile: ci/Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd migrations; `PYTHONPATH=.. alembic upgrade head`'
    env_file:
      - .env
    depends_on:
      - db
  tests:
    image: family_api
    build:
      context: ..
      dockerfile: ci/Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; pytest --html reports/test-report.html tests'
    env_file:
      - .env
    volumes:
      - ./reports:/code/reports
    depends_on:
      - migration
